Homework 2 tests
GenesisEducationKyiv/main-project-MlPablo pull request #3
Opened 2023-06-24 18:20 UTC by MlPablo

1. Added unit tests for services, repo, http handlers. All tests in the same pack as there logic.
2. Added integration and e2e tests. They are located at ./tests dir.

2023-06-25 08:55 UTC, vorobeiDev approved these changes

2023-06-25 08:55 UTC, vorobeiDev commented on tests/e2e/email_service_test.go
> +// func (suite *E2ESuite) TestSendEmail() {
Is it no a needed file?

2023-06-25 11:12 UTC, MlPablo commented on tests/e2e/email_service_test.go
> +// func (suite *E2ESuite) TestSendEmail() {
It's not completed tests. In the next commit will fix this

2023-06-26 10:20 UTC, MlPablo commented on tests/e2e/email_service_test.go
> +// func (suite *E2ESuite) TestSendEmail() {
Fixed in 3-hw pr.

2023-06-27 21:06 UTC, oleksandr-kh requested changes
загалом робота досить непогано, добре попрацював 👍

2023-06-27 21:06 UTC, oleksandr-kh commented on tests/e2e/suite.go
> +package e2e
чому в e2e не зробив тест на /rate ? це було б найкраще рішення саме для тестування реальної середи

2023-06-27 21:06 UTC, oleksandr-kh commented on tests/functional/service_tests.go
> +func (suite *Suite) TestValidCreateUser() {
так виглядає, що тут дублюється перевірки з e2e
я не думаю що в цьому є великий сенс

2023-06-28 17:57 UTC, MlPablo commented on internal/repository/filesystem/file_test.go
> -	email, err := repo.GetByEmail(ctx, testEmail)
Fixed this in third home work.

2023-06-28 17:59 UTC, MlPablo commented on tests/e2e/suite.go
> +package e2e
Made this in 3 home work.

2023-06-28 18:02 UTC, MlPablo commented on tests/functional/service_tests.go
> +func (suite *Suite) TestValidCreateUser() {
Yes, you are right. I thought that functional test must have near the same logic, but with difference in response. Ok, i'll delete this one.

2023-06-28 18:06 UTC, MlPablo commented
The commit with the resolve is in 3 homework pr. This was done due to some refactors, so it's better to push changes into new branch. For now I merge this branch.

2023-06-28 18:13 UTC, merged