Homework 4 patterns
GenesisEducationKyiv/main-project-MlPablo pull request #5
Opened 2023-07-01 16:31 UTC by MlPablo

Added 2 new rate providers: binance.com, coingecko.com.
Added functionality: move to another provider if current has errors( not respond, invalid currency...). Chain of responsibility pattern have been used.
Added logging for crypto providers response. This is an optional field in class constructor.

2023-07-02 14:06 UTC, vorobeiDev approved these changes

2023-07-10 21:59 UTC, oleksandr-kh requested changes

2023-07-10 21:59 UTC, oleksandr-kh commented on internal/infrastructure/currency/binance/binance.go
> +	SetNext(any) error
SetNext(any) - чому any ? ми ж очікуємо інтерфейс Chain
у тебе інтерфейс (один й той самий) дублюється у кожного провайдера 
краще винести кудись на більш базовий рівень у package, наприклад infrastructure/currency/chain.go
і зав'язатись уже в середині провайдерів на нього

2023-07-10 21:59 UTC, oleksandr-kh commented on internal/infrastructure/currency/binance/binance.go
> +	SetNext(any) error
інтерфейс я би краще зробив так:
`type Chain interface {
	ICurrencyService // той самий інтерфейс який зараз тут internal/controller/http/controller.go:19
	SetNext(any) error
}`

сам інтерфейс ICurrencyService - повинен бути у шарі application, а в твоєму випадку він знаходиться у delivery, тому що в тебе delivery і application злиті в один шар
І краще прийти до єдиної структури назви інтерфейсів, а то десь у тебе префікс "I", а десь його немає
можеш обрати підхід який тобі подобається (мені, наприклад, #3 із статті https://medium.com/@dotronglong/interface-naming-convention-in-golang-f53d9f471593)

2023-07-10 21:59 UTC, oleksandr-kh commented on internal/infrastructure/currency/binance/binance.go
> +	if !ok {
з урахуванням попередніх коментарів в тебе не будет цієї дублючої перевірки

2023-07-10 21:59 UTC, oleksandr-kh commented on internal/infrastructure/currency/currencyapi/options.go
> +func WithLogger(logger Logger) Option {
цей майже цілком дублюється у всіх трьох провайдерах - значить можна подумати над іншою реалізацією 😉

2023-07-10 21:59 UTC, oleksandr-kh commented on internal/infrastructure/currency/currencyapi/options.go
> +func WithLogger(logger Logger) Option {
опишу нижче мій варіант

2023-07-10 21:59 UTC, oleksandr-kh commented on internal/infrastructure/currency/coingecko/coingecko.go
> +func NewCoingeckoApi(cfg *Config, opts ...Option) *CoingeckoAPI {
Як рішення я б прокидав client в конструктор, а не створював в середині
таким чином тобі треба буде зробити лише один декоратор на клієнт (http.Client), і в разі необхідності логування - сам клієнт огортати назовні цим декоратором

2023-07-10 22:03 UTC, oleksandr-kh commented
\+ в репозиторії UserRepository метод SaveUser(User) з аргументом User - краще назвати Save(User), і так добре читається)

2023-07-11 06:54 UTC, merged